apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloakpass
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  type: ClusterIP
  selector:
    app: keycloak-db
  ports:
    - port: 5432
      targetPort: 5432
